### ISSUE TITLE
missing file transfer between PC and docker

### ISSUE THREAD

**Issue by kyomawolf** [kyomawolf/42-trascendence#9]
**Description**
creating files in docker dev containers wont be visible on the PC and cannot be used with git.

**To Reproduce**
1. create file in Dev Containers
2. see if file is in normal folder structure

**Comment by toni-schmitt** [comment]
Only Files in `src/` Directory get changed because of the Volume binding in `docker-compose.yml`
https://github.com/kyomawolf/42-trascendence/blob/e25fccf2a286b2eb926488f03938431bbbe1037f/docker/docker-compose.yml#L25 

Do we need to extend the context? In which Scenario would you like to add a File to the root instead of the `src/`?

**Comment by toni-schmitt** [comment]
When changing the context to `/client/` or `/api/` the `node_modules` also get shared, which would be bad for working on 42-Mac's. `node_modules` cannot be excluded. 
This is probably a wontfix, if you really need to change a File in the root change it outside the Dev Container.
